version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend-app
    ports:
      - "3010:3000"
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - CHATBOT_URL=http://chatbot:5000
      - FRONTEND_URL=http://localhost:5183
      - GOOGLE_CALL_BACK=http://localhost:3010/api/v1/auth/google/redirect
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - redis
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-app
    ports:
      - "5183:5173"
    env_file:
      - ./frontend/.env
    environment:
      - VITE_BACKEND_URL=http://localhost:3010
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile.dev
    container_name: admin-app
    ports:
      - "4183:4173"
    env_file:
      - ./admin/.env
    environment:
      - VITE_BACKEND_URL=http://localhost:3010
    volumes:
      - ./admin:/app
      - /app/node_modules
    depends_on:
      - backend

  chatbot:
    build:
      context: ./chatbot
      dockerfile: Dockerfile.dev
    container_name: chatbot-app
    ports:
      - "5000:5000"
    env_file:
      - ./chatbot/.env
    environment:
      - DB_HOST=postgres
      - BACKEND_URL=http://backend:3000
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./chatbot:/app
      - /app/node_modules
    depends_on:
      - postgres
      - backend

  redis:
    image: redis
    container_name: redis-db
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass 123456

  postgres:
    image: postgres:17
    container_name: postgresql_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=booking_doctor_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    restart: always
    depends_on:
      - redis

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-ui
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@local.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "8000:80"
    depends_on:
      - postgres

volumes:
  redis_data:
  postgres_data:
