import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateTable1775112748782 implements MigrationInterface {
    name = 'CreateTable1775112748782'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "notifications" ("id" SERIAL NOT NULL, "content" character varying NOT NULL, "title" character varying NOT NULL, "is_notified" boolean NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "user_id" integer NOT NULL, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "topics" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL, "slug" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_1304b1c61016e63f60cd147ce6b" UNIQUE ("name"), CONSTRAINT "UQ_97c66ab0029f49fde30517f8199" UNIQUE ("slug"), CONSTRAINT "PK_e4aa99a3fa60ec3a37d1fc4e853" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tags" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_d90243459a697eadb8ad56e9092" UNIQUE ("name"), CONSTRAINT "UQ_b3aa10c29ea4e61a830362bd25a" UNIQUE ("slug"), CONSTRAINT "PK_e7dc17249a1148a1970748eda99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "article_tags" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "article_id" integer, "tag_id" integer, CONSTRAINT "UQ_article_tags" UNIQUE ("article_id", "tag_id"), CONSTRAINT "PK_75f74d8cce8a559622dffcc5ae2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "articles" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "content" character varying NOT NULL, "img_urls" jsonb, "summary" character varying NOT NULL, "slug" character varying NOT NULL, "is_approve" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "topic_id" integer NOT NULL, "author_id" integer NOT NULL, CONSTRAINT "UQ_1123ff6815c5b8fec0ba9fec370" UNIQUE ("slug"), CONSTRAINT "PK_0a6e2c450d83e0b6052c2793334" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "specialties" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" character varying NOT NULL, "img_url" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_565f38f8b0417c7dbd40e429782" UNIQUE ("name"), CONSTRAINT "UQ_6678765a8dcfa5597a6cdf71eb0" UNIQUE ("slug"), CONSTRAINT "PK_ba01cec5aa8ac48778a1d097e98" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "examination_result" ("id" SERIAL NOT NULL, "symptoms" character varying NOT NULL, "diagnosis" character varying NOT NULL, "treatment" character varying NOT NULL, "prescription" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "appointment_id" integer NOT NULL, CONSTRAINT "REL_ed9c38177edc3cd6fcc36c815a" UNIQUE ("appointment_id"), CONSTRAINT "PK_dd9f60a977685a1bcbf47b531ad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "satisfaction_rating" ("id" SERIAL NOT NULL, "rating_score" integer NOT NULL, "feedback" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "appointment_id" integer NOT NULL, CONSTRAINT "REL_5f8f7f1dc44f9ed667998078c1" UNIQUE ("appointment_id"), CONSTRAINT "CHK_40d27b1cbd3bd8535ada2e95ed" CHECK ("rating_score" >= 1 AND "rating_score" <= 5), CONSTRAINT "PK_17c22725d340696bcc81bdd0195" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "health_profile" ("id" SERIAL NOT NULL, "weight" integer, "height" integer, "blood_type" character varying, "medical_history" character varying, "allergies" character varying, "heart_rate" integer, "blood_pressure" character varying, "glucose_level" integer, "cholesterol_level" integer, "medications" character varying, "vaccinations" character varying, "smoking" boolean, "alcohol_consumption" boolean, "exercise_frequency" character varying, "last_checkup_date" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "relative_id" integer NOT NULL, CONSTRAINT "REL_ccd502e69a22e29afcb1c375ec" UNIQUE ("relative_id"), CONSTRAINT "CHK_a1bf5e65cb7bf44a477ae1c86d" CHECK ("cholesterol_level" IS NULL OR "cholesterol_level" >= 0), CONSTRAINT "CHK_a49bbc989e61bffbaa94e0b67e" CHECK ("glucose_level" IS NULL OR "glucose_level" >= 0), CONSTRAINT "CHK_b1ca970024df3e97dcc07dcfd9" CHECK ("heart_rate" IS NULL OR "heart_rate" > 0), CONSTRAINT "CHK_c837dca92f01903244926150d4" CHECK ("height" IS NULL OR "height" > 0), CONSTRAINT "CHK_09d708a21242c63911349c4507" CHECK ("weight" IS NULL OR "weight" > 0), CONSTRAINT "PK_d7a095a2b692da5ebbb7ee95b2e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "relationships" ("id" SERIAL NOT NULL, "relationship_code" character varying NOT NULL, "relationship_name" character varying NOT NULL, "description" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_600f621e0ed63ad1c50f2c2d4fa" UNIQUE ("relationship_code"), CONSTRAINT "UQ_528174215bb9eb0113323cdc93a" UNIQUE ("relationship_name"), CONSTRAINT "PK_ba20e2f5cf487408e08e4dcecaf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "relatives" ("id" SERIAL NOT NULL, "fullname" character varying, "phone" character varying, "dob" date, "gender" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "user_id" integer NOT NULL, "relationship_code" character varying NOT NULL, CONSTRAINT "PK_4c16d30b6af847a1f7286caf2c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."appointment_status" AS ENUM('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'ABSENT')`);
        await queryRunner.query(`CREATE TYPE "public"."booking_mode" AS ENUM('user_select', 'ai_select')`);
        await queryRunner.query(`CREATE TABLE "appointments" ("id" SERIAL NOT NULL, "appointment_date" TIMESTAMP NOT NULL, "status" "public"."appointment_status" NOT NULL DEFAULT 'PENDING', "booking_mode" "public"."booking_mode" NOT NULL DEFAULT 'user_select', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "doctor_schedule_id" integer NOT NULL, "patient_id" integer NOT NULL, "user_id" integer NOT NULL, CONSTRAINT "PK_4a437a9a27e948726b8bb3e36ad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."day_of_week" AS ENUM('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday')`);
        await queryRunner.query(`CREATE TABLE "doctor_schedules" ("id" SERIAL NOT NULL, "day_of_week" "public"."day_of_week" NOT NULL, "start_time" TIME NOT NULL, "end_time" TIME NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "doctor_id" integer NOT NULL, CONSTRAINT "UQ_doctor_schedules" UNIQUE ("doctor_id", "day_of_week", "start_time", "end_time"), CONSTRAINT "PK_a1cab57bc0a680b50d06930b377" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."doctors_doctor_level_enum" AS ENUM('Bác sĩ đa khoa', 'Bác sĩ chuyên khoa I', 'Bác sĩ chuyên khoa II', 'Thạc sĩ', 'Tiến sĩ', 'Phó Giáo sư', 'Giáo sư')`);
        await queryRunner.query(`CREATE TABLE "doctors" ("id" SERIAL NOT NULL, "experience" integer NOT NULL, "about_me" character varying NOT NULL, "workplace" character varying NOT NULL, "doctor_level" "public"."doctors_doctor_level_enum" NOT NULL DEFAULT 'Bác sĩ đa khoa', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "specialty_id" integer, "user_id" integer, CONSTRAINT "REL_653c27d1b10652eb0c7bbbc442" UNIQUE ("user_id"), CONSTRAINT "PK_8207e7889b50ee3695c2b8154ff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."role_message" AS ENUM('human', 'ai')`);
        await queryRunner.query(`CREATE TABLE "conversation" ("id" SERIAL NOT NULL, "role" "public"."role_message" NOT NULL DEFAULT 'human', "content" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "user_id" integer, CONSTRAINT "PK_864528ec4274360a40f66c29845" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "otps" ("id" SERIAL NOT NULL, "otpCode" character varying NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "verified" boolean NOT NULL DEFAULT false, "user_id" integer, CONSTRAINT "UQ_20c5c6d5587eee065b40941a785" UNIQUE ("otpCode"), CONSTRAINT "PK_91fef5ed60605b854a2115d2410" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "channel_members" ("id" SERIAL NOT NULL, "participant_id" integer, "channel_id" integer NOT NULL, CONSTRAINT "UQ_channel_members" UNIQUE ("channel_id", "participant_id"), CONSTRAINT "PK_95976b619edca48aed364c70c36" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "channels" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_bc603823f3f741359c2339389f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."file_type" AS ENUM('VIDEO', 'IMAGE', 'DOCUMENT', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "messages_attachments" ("id" SERIAL NOT NULL, "url" character varying, "type" "public"."file_type" NOT NULL DEFAULT 'IMAGE', "file_name" character varying NOT NULL, "file_size" integer NOT NULL, "file_extension" character varying NOT NULL, "public_id" character varying NOT NULL, "message_id" integer, CONSTRAINT "UQ_8b2f3255c9a3617ffbe1b9efbed" UNIQUE ("public_id"), CONSTRAINT "PK_068bf8bc014f3d8403aeec5d2c7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."message_type" AS ENUM('regular', 'call')`);
        await queryRunner.query(`CREATE TABLE "messages" ("id" SERIAL NOT NULL, "message_type" "public"."message_type" NOT NULL, "content" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "sender_id" integer NOT NULL, "channel_id" integer, CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."complaint_status" AS ENUM('pending', 'in_progress', 'resolved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "complaints" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "description" character varying NOT NULL, "complaint_status" "public"."complaint_status" NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "user_id" integer, CONSTRAINT "PK_4b7566a2a489c2cc7c12ed076ad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_log" ("id" SERIAL NOT NULL, "action" character varying NOT NULL, "entity_type" character varying NOT NULL, "old_data" jsonb NOT NULL, "new_data" jsonb NOT NULL, "endpoint" character varying NOT NULL, "method" character varying NOT NULL, "status_code" integer NOT NULL, "is_success" boolean NOT NULL DEFAULT false, "error_message" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" integer NOT NULL, CONSTRAINT "PK_07fefa57f7f5ab8fc3f52b3ed0b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "username" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying, "phone" character varying, "fullname" character varying, "gender" boolean NOT NULL DEFAULT true, "date_of_birth" TIMESTAMP, "picture" character varying, "address" character varying, "isAdmin" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_a000cca60bcf04454e727699490" UNIQUE ("phone"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_48ce552495d14eae9b187bb6716" UNIQUE ("name"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "role_id" integer NOT NULL, "permission_id" integer, CONSTRAINT "UQ_role_permissions" UNIQUE ("role_id", "permission_id"), CONSTRAINT "PK_84059017c90bfcb701b8fa42297" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" SERIAL NOT NULL, "role_name" character varying NOT NULL, "description" character varying NOT NULL, "role_code" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_ac35f51a0f17e3e1fe121126039" UNIQUE ("role_name"), CONSTRAINT "UQ_3feee96f9a604421f24496988db" UNIQUE ("role_code"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_roles" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "user_id" integer, "role_id" integer, CONSTRAINT "UQ_user_roles" UNIQUE ("user_id", "role_id"), CONSTRAINT "PK_8acd5cf26ebd158416f477de799" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "article_tags" ADD CONSTRAINT "FK_f8c9234a4c4cb37806387f0c9e9" FOREIGN KEY ("article_id") REFERENCES "articles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "article_tags" ADD CONSTRAINT "FK_1325dd0b98ee0f8f673db6ce194" FOREIGN KEY ("tag_id") REFERENCES "tags"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "articles" ADD CONSTRAINT "FK_339ac5a85fd438b19f3466ddb2f" FOREIGN KEY ("topic_id") REFERENCES "topics"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "articles" ADD CONSTRAINT "FK_6515da4dff8db423ce4eb841490" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "examination_result" ADD CONSTRAINT "FK_ed9c38177edc3cd6fcc36c815ac" FOREIGN KEY ("appointment_id") REFERENCES "appointments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "satisfaction_rating" ADD CONSTRAINT "FK_5f8f7f1dc44f9ed667998078c14" FOREIGN KEY ("appointment_id") REFERENCES "appointments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "health_profile" ADD CONSTRAINT "FK_ccd502e69a22e29afcb1c375ec1" FOREIGN KEY ("relative_id") REFERENCES "relatives"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "relatives" ADD CONSTRAINT "FK_4cbde7eae8b44b16095dade8ed9" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "relatives" ADD CONSTRAINT "FK_c6a0e99173585f22c76eac3adf5" FOREIGN KEY ("relationship_code") REFERENCES "relationships"("relationship_code") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_4326b7f506e06afb92c4919136f" FOREIGN KEY ("doctor_schedule_id") REFERENCES "doctor_schedules"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_3330f054416745deaa2cc130700" FOREIGN KEY ("patient_id") REFERENCES "relatives"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointments" ADD CONSTRAINT "FK_66dee3bea82328659a4db8e54b7" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doctor_schedules" ADD CONSTRAINT "FK_a9562c0e3b99e62425d3356c88b" FOREIGN KEY ("doctor_id") REFERENCES "doctors"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD CONSTRAINT "FK_67d7cd9e927b1dca13d42511c02" FOREIGN KEY ("specialty_id") REFERENCES "specialties"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doctors" ADD CONSTRAINT "FK_653c27d1b10652eb0c7bbbc4427" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversation" ADD CONSTRAINT "FK_0825886afb03b1a6f11345b4e8c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "otps" ADD CONSTRAINT "FK_3938bb24b38ad395af30230bded" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "channel_members" ADD CONSTRAINT "FK_97f20555459c3b247d388c002af" FOREIGN KEY ("participant_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "channel_members" ADD CONSTRAINT "FK_71a10831469775a1effdd85f240" FOREIGN KEY ("channel_id") REFERENCES "channels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages_attachments" ADD CONSTRAINT "FK_9dcb4e328012fbd884cc6f2f23a" FOREIGN KEY ("message_id") REFERENCES "messages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_22133395bd13b970ccd0c34ab22" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_86b9109b155eb70c0a2ca3b4b6d" FOREIGN KEY ("channel_id") REFERENCES "channels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "complaints" ADD CONSTRAINT "FK_250ea1d40f7a564243d77705e09" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_log" ADD CONSTRAINT "FK_cb11bd5b662431ea0ac455a27d7" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "audit_log" DROP CONSTRAINT "FK_cb11bd5b662431ea0ac455a27d7"`);
        await queryRunner.query(`ALTER TABLE "complaints" DROP CONSTRAINT "FK_250ea1d40f7a564243d77705e09"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_86b9109b155eb70c0a2ca3b4b6d"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_22133395bd13b970ccd0c34ab22"`);
        await queryRunner.query(`ALTER TABLE "messages_attachments" DROP CONSTRAINT "FK_9dcb4e328012fbd884cc6f2f23a"`);
        await queryRunner.query(`ALTER TABLE "channel_members" DROP CONSTRAINT "FK_71a10831469775a1effdd85f240"`);
        await queryRunner.query(`ALTER TABLE "channel_members" DROP CONSTRAINT "FK_97f20555459c3b247d388c002af"`);
        await queryRunner.query(`ALTER TABLE "otps" DROP CONSTRAINT "FK_3938bb24b38ad395af30230bded"`);
        await queryRunner.query(`ALTER TABLE "conversation" DROP CONSTRAINT "FK_0825886afb03b1a6f11345b4e8c"`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP CONSTRAINT "FK_653c27d1b10652eb0c7bbbc4427"`);
        await queryRunner.query(`ALTER TABLE "doctors" DROP CONSTRAINT "FK_67d7cd9e927b1dca13d42511c02"`);
        await queryRunner.query(`ALTER TABLE "doctor_schedules" DROP CONSTRAINT "FK_a9562c0e3b99e62425d3356c88b"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_66dee3bea82328659a4db8e54b7"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_3330f054416745deaa2cc130700"`);
        await queryRunner.query(`ALTER TABLE "appointments" DROP CONSTRAINT "FK_4326b7f506e06afb92c4919136f"`);
        await queryRunner.query(`ALTER TABLE "relatives" DROP CONSTRAINT "FK_c6a0e99173585f22c76eac3adf5"`);
        await queryRunner.query(`ALTER TABLE "relatives" DROP CONSTRAINT "FK_4cbde7eae8b44b16095dade8ed9"`);
        await queryRunner.query(`ALTER TABLE "health_profile" DROP CONSTRAINT "FK_ccd502e69a22e29afcb1c375ec1"`);
        await queryRunner.query(`ALTER TABLE "satisfaction_rating" DROP CONSTRAINT "FK_5f8f7f1dc44f9ed667998078c14"`);
        await queryRunner.query(`ALTER TABLE "examination_result" DROP CONSTRAINT "FK_ed9c38177edc3cd6fcc36c815ac"`);
        await queryRunner.query(`ALTER TABLE "articles" DROP CONSTRAINT "FK_6515da4dff8db423ce4eb841490"`);
        await queryRunner.query(`ALTER TABLE "articles" DROP CONSTRAINT "FK_339ac5a85fd438b19f3466ddb2f"`);
        await queryRunner.query(`ALTER TABLE "article_tags" DROP CONSTRAINT "FK_1325dd0b98ee0f8f673db6ce194"`);
        await queryRunner.query(`ALTER TABLE "article_tags" DROP CONSTRAINT "FK_f8c9234a4c4cb37806387f0c9e9"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "audit_log"`);
        await queryRunner.query(`DROP TABLE "complaints"`);
        await queryRunner.query(`DROP TYPE "public"."complaint_status"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP TYPE "public"."message_type"`);
        await queryRunner.query(`DROP TABLE "messages_attachments"`);
        await queryRunner.query(`DROP TYPE "public"."file_type"`);
        await queryRunner.query(`DROP TABLE "channels"`);
        await queryRunner.query(`DROP TABLE "channel_members"`);
        await queryRunner.query(`DROP TABLE "otps"`);
        await queryRunner.query(`DROP TABLE "conversation"`);
        await queryRunner.query(`DROP TYPE "public"."role_message"`);
        await queryRunner.query(`DROP TABLE "doctors"`);
        await queryRunner.query(`DROP TYPE "public"."doctors_doctor_level_enum"`);
        await queryRunner.query(`DROP TABLE "doctor_schedules"`);
        await queryRunner.query(`DROP TYPE "public"."day_of_week"`);
        await queryRunner.query(`DROP TABLE "appointments"`);
        await queryRunner.query(`DROP TYPE "public"."booking_mode"`);
        await queryRunner.query(`DROP TYPE "public"."appointment_status"`);
        await queryRunner.query(`DROP TABLE "relatives"`);
        await queryRunner.query(`DROP TABLE "relationships"`);
        await queryRunner.query(`DROP TABLE "health_profile"`);
        await queryRunner.query(`DROP TABLE "satisfaction_rating"`);
        await queryRunner.query(`DROP TABLE "examination_result"`);
        await queryRunner.query(`DROP TABLE "specialties"`);
        await queryRunner.query(`DROP TABLE "articles"`);
        await queryRunner.query(`DROP TABLE "article_tags"`);
        await queryRunner.query(`DROP TABLE "tags"`);
        await queryRunner.query(`DROP TABLE "topics"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
    }

}
