import {
  BellRing,
  BookOpenText,
  CalendarCheck2,
  CalendarClock,
  ClipboardList,
  FileBadge2,
  FileHeart,
  FolderKanban,
  LayoutDashboard,
  MessageSquareHeart,
  ShieldCheck,
  Siren,
  Stethoscope,
  Tags,
  UserCog,
  UserRoundSearch,
  Users,
  UsersRound,
} from "lucide-react";

import { permissions } from "@/config/permissions";
import type { MenuItem } from "@/types/app";

export const menuItems: MenuItem[] = [
  {
    id: "doctor-dashboard",
    label: "Dashboard",
    path: "/doctor/dashboard",
    section: "Doctor workspace",
    icon: LayoutDashboard,
    requiredPermissions: [permissions.doctorDashboard],
  },
  {
    id: "doctor-schedules",
    label: "Doctor schedule",
    path: "/doctor/schedules",
    section: "Doctor workspace",
    icon: CalendarClock,
    requiredPermissions: [permissions.doctorSchedules],
    moduleId: "doctor-schedules",
  },
  {
    id: "doctor-appointments",
    label: "Lịch khám bác sĩ",
    path: "/doctor/appointments",
    section: "Doctor workspace",
    icon: CalendarCheck2,
    requiredPermissions: [permissions.doctorAppointments],
    moduleId: "doctor-appointments",
  },
  {
    id: "doctor-tags",
    label: "Quản lý Tag",
    path: "/doctor/tags",
    section: "Content",
    icon: Tags,
    requiredPermissions: [permissions.tags],
    moduleId: "tags",
  },
  {
    id: "doctor-articles",
    label: "Quản lý bài viết",
    path: "/doctor/articles",
    section: "Content",
    icon: BookOpenText,
    requiredPermissions: [permissions.articles],
    moduleId: "articles",
  },
  {
    id: "doctor-topics",
    label: "Quản lý topic",
    path: "/doctor/topics",
    section: "Content",
    icon: FolderKanban,
    requiredPermissions: [permissions.topics],
    moduleId: "topics",
  },
  {
    id: "doctor-messages",
    label: "Messages",
    path: "/doctor/messages",
    section: "Clinical comms",
    icon: MessageSquareHeart,
    requiredPermissions: [permissions.doctorMessages],
  },
  {
    id: "doctor-records",
    label: "Tóm tắt bệnh án",
    path: "/doctor/patient-records",
    section: "Clinical comms",
    icon: FileHeart,
    requiredPermissions: [permissions.patientRecords],
    moduleId: "patient-records",
  },
  {
    id: "doctor-patients",
    label: "Quản lý bệnh nhân",
    path: "/doctor/patients",
    section: "Clinical comms",
    icon: UsersRound,
    requiredPermissions: [permissions.patients],
    moduleId: "patients",
  },
  {
    id: "doctor-settings",
    label: "Settings",
    path: "/doctor/settings",
    section: "Doctor workspace",
    icon: UserCog,
    requiredPermissions: [permissions.doctorSettings],
  },
  {
    id: "admin-dashboard",
    label: "Dashboard",
    path: "/admin/dashboard",
    section: "Admin operations",
    icon: LayoutDashboard,
    requiredPermissions: [permissions.adminDashboard],
  },
  {
    id: "admin-users",
    label: "Quản lý người dùng",
    path: "/admin/users",
    section: "Admin operations",
    icon: Users,
    requiredPermissions: [permissions.users],
    moduleId: "users",
  },
  {
    id: "admin-patients",
    label: "Quản lý bệnh nhân",
    path: "/admin/patients",
    section: "Clinical data",
    icon: UsersRound,
    requiredPermissions: [permissions.adminPatients],
    moduleId: "admin-patients",
  },
  {
    id: "admin-doctors",
    label: "Quản lý bác sĩ",
    path: "/admin/doctors",
    section: "Admin operations",
    icon: Stethoscope,
    requiredPermissions: [permissions.doctors],
    moduleId: "doctors",
  },
  {
    id: "admin-tags",
    label: "Quản lý tag",
    path: "/admin/tags",
    section: "Content",
    icon: Tags,
    requiredPermissions: [permissions.tags],
    moduleId: "tags",
  },
  {
    id: "admin-topics",
    label: "Quản lý topic",
    path: "/admin/topics",
    section: "Content",
    icon: FolderKanban,
    requiredPermissions: [permissions.topics],
    moduleId: "topics",
  },
  {
    id: "admin-articles",
    label: "Quản lý bài viết",
    path: "/admin/articles",
    section: "Content",
    icon: BookOpenText,
    requiredPermissions: [permissions.articles],
    moduleId: "articles",
  },
  {
    id: "admin-appointments",
    label: "Quản lý lịch hẹn khám",
    path: "/admin/appointments",
    section: "Admin operations",
    icon: ClipboardList,
    requiredPermissions: [permissions.appointments],
    moduleId: "appointments",
  },
  {
    id: "admin-role-permissions",
    label: "Quản lý phân quyền vai trò",
    path: "/admin/role-permissions",
    section: "Governance",
    icon: ShieldCheck,
    requiredPermissions: [permissions.rolePermissions],
    moduleId: "role-permissions",
  },
  {
    id: "admin-ratings",
    label: "Quản lý đánh giá",
    path: "/admin/ratings",
    section: "Governance",
    icon: FileBadge2,
    requiredPermissions: [permissions.ratings],
    moduleId: "ratings",
  },
  {
    id: "admin-exam-results",
    label: "Quản lý kết quả khám",
    path: "/admin/exam-results",
    section: "Clinical data",
    icon: FileHeart,
    requiredPermissions: [permissions.examResults],
    moduleId: "exam-results",
  },
  {
    id: "admin-relatives",
    label: "Quản lý người thân",
    path: "/admin/relatives",
    section: "Clinical data",
    icon: UsersRound,
    requiredPermissions: [permissions.relatives],
    moduleId: "relatives",
  },
  {
    id: "admin-audit-logs",
    label: "Quản lý auditlogs",
    path: "/admin/audit-logs",
    section: "Governance",
    icon: Siren,
    requiredPermissions: [permissions.auditLogs],
    moduleId: "audit-logs",
  },
  {
    id: "admin-health-profiles",
    label: "Quản lý hồ sơ sức khỏe",
    path: "/admin/health-profiles",
    section: "Clinical data",
    icon: FileHeart,
    requiredPermissions: [permissions.healthProfiles],
    moduleId: "health-profiles",
  },
  {
    id: "admin-relationships",
    label: "Quản lý quan hệ",
    path: "/admin/relationships",
    section: "Clinical data",
    icon: UserRoundSearch,
    requiredPermissions: [permissions.relationships],
    moduleId: "relationships",
  },
  {
    id: "admin-specialties",
    label: "Quản lý chuyên khoa",
    path: "/admin/specialties",
    section: "Clinical data",
    icon: Stethoscope,
    requiredPermissions: [permissions.specialties],
    moduleId: "specialties",
  },
  {
    id: "admin-complaints",
    label: "Quản lý các phản hồi",
    path: "/admin/complaints",
    section: "Governance",
    icon: MessageSquareHeart,
    requiredPermissions: [permissions.complaints],
    moduleId: "complaints",
  },
  {
    id: "admin-notifications",
    label: "Quản lý thông báo",
    path: "/admin/notifications",
    section: "Governance",
    icon: BellRing,
    requiredPermissions: [permissions.notifications],
    moduleId: "notifications",
  },
  {
    id: "admin-settings",
    label: "Settings",
    path: "/admin/settings",
    section: "System",
    icon: UserCog,
    requiredPermissions: [permissions.settings],
  },
];
