export const permissions = {
  doctorDashboard: "doctor.dashboard.read",
  doctorSchedules: "doctor.schedules.manage",
  doctorAppointments: "doctor.appointments.manage",
  tags: "content.tags.manage",
  articles: "content.articles.manage",
  topics: "content.topics.manage",
  doctorMessages: "doctor.messages.manage",
  patientRecords: "doctor.patient-records.manage",
  patients: "doctor.patients.manage",
  doctorSettings: "doctor.settings.manage",
  adminDashboard: "admin.dashboard.read",
  users: "admin.users.manage",
  adminPatients: "admin.patients.manage",
  doctors: "admin.doctors.manage",
  appointments: "admin.appointments.manage",
  rolePermissions: "admin.role-permissions.manage",
  ratings: "admin.ratings.manage",
  examResults: "admin.examination-results.manage",
  relatives: "admin.relatives.manage",
  auditLogs: "admin.audit-logs.manage",
  healthProfiles: "admin.health-profiles.manage",
  relationships: "admin.relationships.manage",
  specialties: "admin.specialties.manage",
  complaints: "admin.complaints.manage",
  notifications: "admin.notifications.manage",
  settings: "system.settings.manage",
} as const;

export const doctorPermissionSet = [
  permissions.doctorDashboard,
  permissions.doctorSchedules,
  permissions.doctorAppointments,
  permissions.tags,
  permissions.articles,
  permissions.topics,
  permissions.doctorMessages,
  permissions.patientRecords,
  permissions.patients,
  permissions.doctorSettings,
];

export const adminPermissionSet = [
  permissions.adminDashboard,
  permissions.users,
  permissions.adminPatients,
  permissions.doctors,
  permissions.tags,
  permissions.topics,
  permissions.articles,
  permissions.appointments,
  permissions.rolePermissions,
  permissions.ratings,
  permissions.examResults,
  permissions.relatives,
  permissions.auditLogs,
  permissions.healthProfiles,
  permissions.relationships,
  permissions.specialties,
  permissions.complaints,
  permissions.notifications,
  permissions.settings,
];
