export enum NotificationType {
  MANUAL = 'MANUAL',
  APPOINTMENT_CREATED = 'APPOINTMENT_CREATED',
  APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
  APPOINTMENT_STATUS_UPDATED = 'APPOINTMENT_STATUS_UPDATED',
  APPOINTMENT_EXPIRED = 'APPOINTMENT_EXPIRED',
  APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',
}
